Create `installation` branch
Create branch to test BLUEMIRA installation. Scripts in the `examples` directory
have been tested, with the exception of the `examples/codes` folder, since
integration with the PLASMOD project still needs to be performed.

WORKING BLUEMIRA examples:

- balance_of_plant/steady_state_example.py

- base/components_tutorial.py

- design/design_shapes.py
- design/design_shapes.ipynb

- equilibria/eudemo_2017.py (with warnings)

- equilibria/single_null.py (with warnings)

- fuel_cycle/EUDEMO_fuelcycle.py

- geometry/geometry_tutorial.py
- geometry/geometry_tutorial.ipynb

- geometry/optimisation_tutotial.py

- geometry/plotting_tutorial.py
- geometry/plotting_tutorial.ipynb

- magnetostatics/helmholtz_example.py

- materials/material_definitions.py

- radiation_transport/heat_flux_calculation.py

- radiation_transport/heat_flux_calculation_DN.py

- utilities/optimisation_example.py

NOT WORKING BLUEMIRA examples:

0. BLUEPRINT_integration.py
```
+-------------------------------------------------------------------------+
| WARNING: The source of the value of c_rm not consistently known         |
+-------------------------------------------------------------------------+
Traceback (most recent call last):
  File "/Users/tiago/Documents/VSCODE/bluemira/examples/BLUEPRINT_integration.p
	y", line 434, in <module> reactor.build()
  File "/Users/tiago/Documents/VSCODE/bluemira/BLUEPRINT/reactor.py", line 271,
	in build self.build_TF_coils()
  File "/Users/tiago/Documents/VSCODE/bluemira/examples/BLUEPRINT_integration.p
	y", line 284, in build_TF_coils super().build_TF_coils(
  File "/Users/tiago/Documents/VSCODE/bluemira/BLUEPRINT/reactor.py", line 691,
	in build_TF_coils conductivity = self.build_config["conductivity"]
KeyError: 'conductivity'
```

1. design/EU-DEMO/EUDEMO_reactor.py
```
Traceback (most recent call last):
  File "/Users/tiago/Documents/VSCODE/bluemira/examples/design/EU-DEMO/EUDEMO_re
	actor.py", line 48, in <module> from bluemira.equilibria.run import AbInitio
	EquilibriumProblem
ModuleNotFoundError: No module named 'bluemira.equilibria.run'
```

2. design/EU-DEMO/EUDEMO_reactor.ipynb (CELL 1)
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/Users/tiago/Documents/VSCODE/bluemira/examples/design/EU-DEMO/EUDEMO_reactor.ip
	ynb Cell 1' in <module>
     20 from bluemira.codes.process.mapping import mappings as PROCESS_mappings
	# noqa: N812
     21 from bluemira.display.displayer import ComponentDisplayer
---> 22 from bluemira.equilibria.run import AbInitioEquilibriumProblem
     23 from bluemira.utilities.tools import json_writer

ModuleNotFoundError: No module named 'bluemira.equilibria.run'
```

3. equilibria/eudemo_2017.ipynb (CELL 4)
Section "Define parameters" does not complete in 10+ minutes.

4. equilibria/single_null.ipynb (CELL 7)
Cell delimitation was incorrect and some `import commands` were not recognized.
This has been fixed.
Section "Get an initial unconstrained solution") does not complete in 10+
minutes.

5. equilibria/double_null_ST.py
Script does not seem to be made for running.

6. materials/material_definitions.ipynb (CELL 1)
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/Users/tiago/Documents/VSCODE/bluemira/examples/materials/material_definitions.i
	pynb Cell 1' in <module>
----> 1 from bluemira.materials import MaterialCache

ModuleNotFoundError: No module named 'bluemira'
```